# Generated by Django 3.1.7 on 2021-08-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='surname',
            field=models.TextField(null=True),
        ),
    ]
