# Generated by Django 3.1.7 on 2021-08-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210811_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='my_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
