# Generated by Django 3.1.7 on 2021-11-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
