# Generated by Django 3.1.7 on 2021-11-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211101_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.camera')),
            ],
        ),
    ]
