# Generated by Django 3.1.7 on 2021-11-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211121_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
