# Generated by Django 3.1.7 on 2021-11-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.TextField(default='qwe'),
        ),
    ]
