# Generated by Django 3.1.7 on 2021-11-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20211107_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='midname',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.TextField(default=''),
        ),
    ]
