# Generated by Django 3.1.7 on 2021-06-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='midname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='visitcard',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='visitcard',
            name='surname',
            field=models.TextField(default=''),
        ),
    ]
