# Generated by Django 3.1.7 on 2021-06-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0003_geopos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopos',
            name='lattitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='geopos',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
