# Generated by Django 3.1.7 on 2021-06-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0004_auto_20210615_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visitCards.visitcard'),
        ),
    ]
