# Generated by Django 3.1.7 on 2021-06-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0005_auto_20210623_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='geo_descr',
            field=models.TextField(default='Мой офис: '),
        ),
        migrations.AddField(
            model_name='visitcard',
            name='photo_descr',
            field=models.TextField(default='Мои фото: '),
        ),
        migrations.AddField(
            model_name='visitcard',
            name='project_descr',
            field=models.TextField(default='Мои проекты: '),
        ),
    ]
