# Generated by Django 3.1.7 on 2021-06-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0006_auto_20210626_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='theme',
            field=models.TextField(default='Dark'),
        ),
    ]
