# Generated by Django 3.1.7 on 2021-07-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0007_visitcard_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='full_profile_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
