# Generated by Django 3.1.7 on 2021-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0008_visitcard_full_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='x_logo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='visitcard',
            name='y_logo',
            field=models.FloatField(default=0),
        ),
    ]
