# Generated by Django 3.1.7 on 2021-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0009_auto_20210709_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='zoom_logo',
            field=models.FloatField(default=1.3),
        ),
    ]
