# Generated by Django 3.1.7 on 2021-07-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0010_visitcard_zoom_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='verb_id',
            field=models.TextField(max_length=20, null=True, unique=True),
        ),
    ]
