# Generated by Django 3.1.7 on 2021-07-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0012_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visitCards.visitcard'),
        ),
    ]
