# Generated by Django 3.1.7 on 2021-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0013_auto_20210717_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='block_descr',
            field=models.TextField(default='CV'),
        ),
    ]
