# Generated by Django 3.1.7 on 2021-07-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0014_visitcard_block_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='inst_link',
            field=models.TextField(default='instagram.com/', null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tg_link',
            field=models.TextField(default='t.me/', null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='twitter_link',
            field=models.TextField(default='twitter.com/', null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vk_link',
            field=models.TextField(default='vk.com/', null=True),
        ),
    ]
