# Generated by Django 3.1.7 on 2021-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0015_auto_20210720_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='main_part',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='descr',
            field=models.TextField(max_length=50),
        ),
    ]
