# Generated by Django 3.1.7 on 2021-07-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0017_auto_20210721_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp_link',
            field=models.TextField(null=True),
        ),
    ]
