# Generated by Django 3.1.7 on 2021-07-24 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitCards', '0018_auto_20210721_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitcard',
            name='user',
        ),
        migrations.AddField(
            model_name='visitcard',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
