# Generated by Django 3.1.7 on 2021-07-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0019_auto_20210724_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='main_part',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
