# Generated by Django 3.1.7 on 2021-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCards', '0020_auto_20210730_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='inst_username',
            field=models.TextField(null=True),
        ),
    ]
